# Define force field format
format = "GROMACS"

# Define force field
[atoms.OH_tip3p]
name = "OH_tip3p"
mass = 15.9994
epsilon = 0.1521
sigma = 0.315061
cut = 12.0
charge = -0.834
atom_no = 8

[atoms.cH_tip3p]
name = "cH_tip3p"
mass = 1.00784
epsilon = 0.0
sigma = 1.0
cut = 12.0
charge = 0.417
atom_no = 1

[bonds."[OH_tip3p][cH_tip3p]"]
list = [ "OH_tip3p", "cH_tip3p"]
p = [ 0.09572, 376560.0 ]
style = 1

[angles."[cH_tip3p][OH_tip3p][cH_tip3p]"]
list = [ "cH_tip3p", "OH_tip3p","cH_tip3p"]
p = [ 104.52, 460.24 ]
style = 1

[torsions."[dummy][dummy][dummy][dummy]"]
list = [ "dummy", "dummy", "dummy", "dummy",]
p = [ 0.0,0.0,0.0,0.0, 0.0,]
style = 1